### ISSUE TITLE
Not working ?!

### ISSUE THREAD

**Issue by xstable** [doitlikejustin/amazon-wish-lister#27] opened 2016-12-19 19:16 UTC
Did the script still not working or does I use it in wrong way.

http://www.justinscarpetti.com/projects/amazon-wish-lister/api/?id=B0002FTH66 give "Null", like each other Wishlist-ID I add.

**Comment by vishalchhodwani1992** [comment] 2017-01-25 06:33
I am facing the same issue. it is not working.

**Comment by flowdee** [comment] 2017-01-25 08:26
I assume the problem is simply the fact that Amazon added captcha to their sites whichblocks this script from fetching the data 👎

**Comment by doitlikejustin** [comment] 2017-01-26 23:32
Merged with #28

**Closed as completed by doitlikejustin** 2017-01-26 23:32 UTC
